<?php
/**
 * All configs.
 * Do not edit this file.
 * @author Bryce<lushaoming6@gmail.com>
 * @date   2019/12/12
 */
namespace Bryce\OpenApi\Common;

class Config
{
    const CONFIGS = [
        'domain' => 'http://core.lushaoming.site',
        'permissions' => ['send_sms', 'send_email'],
        'sign_method' => 'md5',
        'send_email_url' => 'http://core.lushaoming.site/api/mailer/send',
        'send_sms_url' => 'http://core.lushaoming.site/api/sms/send-verify-code',
        'verify_sms_code_url' => 'http://core.lushaoming.site/api/sms/verify-code',
    ];

    public static function getConfigs()
    {
        return self::CONFIGS;
    }
}